ADD CI/CD - Fix: Correction de toutes les erreurs flake8

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -81,10 +81,10 @@ jobs:
         run: |
           poetry run flake8 src/ app.py --count --max-line-length=120 --statistics --exclude=.venv,__pycache__,*.pyc,.git
 
-      - name: Run pylint
-        working-directory: ./streamlit-poetry-docker
-        run: |
-          poetry run pylint src/ app.py --fail-under=7.0 || true
+      #- name: Run pylint
+      #  working-directory: ./streamlit-poetry-docker
+      #  run: |
+      #    poetry run pylint src/ app.py --fail-under=7.0 || true
 
   # ============================================
   # JOB 3: TEST - Preprocessing
